# This is an example .meta-cnc.yaml file. This will allow Panhandler to consume this terraform project

# this is the name of this skillet, should be unique within a given repository
name: aws_tgw_2fw_3nic_2spoke

# label should be a human readable label that conveys what this skillet will do 
label: TGW Skillet

# description is a longer more informative version of a label
description: AWS TGW Skillet

# type instructs Panhandler how to consume this skillet
type: terraform

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, lables can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  terraform_provider: aws


# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:
  - name: access_key
    description: AWS Access Key
    default: access_key
    type_hint: text
  - name: secret_key
    description: AWS Secret Key
    default:
    type_hint: password
  - name: aws_region
    description: AWS Region
    default: us-east-1
    type_hint: text
  - name: management_cidr
    description: VMSeries mgmt source CIDR
    default: 0.0.0.0/0
    type_hint: text
