# This is an example .meta-cnc.yaml file. This will allow Panhandler to consume this terraform project

# this is the name of this skillet, should be unique within a given repository
name: tgw_2fw_vpc_insertion

# label should be a human readable label that conveys what this skillet will do 
label: AWS TGW Demo

# description is a longer more informative version of a label
description: Creates 2 VM-Series (fully configured) with 2 Spoke VPCs connected to a TGW

# type instructs Panhandler how to consume this skillet
type: terraform

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, lables can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  terraform_provider: aws


# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:
    - name: aws_region
      description: Region
      default: us-east-1
      type_hint: text
    - name: access_key
      description: AWS Access Key
      default: 
      type_hint: text
    - name: secret_key
      description: AWS Secret Key
      default: tenant_id
      type_hint: text
    - name: aws_key
      description: EC2 Keypair Name
      default:
      type_hint: text
    - name: ngfw_license_type
      description: FW License
      default:
      type_hint: dropdown
      dd_list:
       - key: BYOL
         value: byol
       - key: PAYG-Bundle1
         value: payg1
       - key: PAYG-Bundle2
         value: payg2
    - name: management_cidr
      description: FW SG Source Prefix
      default: "0.0.0.0/0"
      type_hint: text