# This is an example .meta-cnc.yaml file. This will allow Panhandler to consume this terraform project

# this is the name of this skillet, should be unique within a given repository
name: azure_multifw_3nic_intlb_extlb

# label should be a human readable label that conveys what this skillet will do 
label: Azure Multi-FW

# description is a longer more informative version of a label
description: Creates multiple firewalls with optional public & internal load balancers.

# type instructs Panhandler how to consume this skillet
type: terraform

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, lables can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  terraform_provider: azure


# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:
    - name: subscription_id
      description: Azure Subscription ID
      default: client_secret
      type_hint: text
    - name: client_id
      description: Azure Client ID
      default: client_id
      type_hint: text
    - name: client_secret
      description: Azure Client Secret
      default: client_secret
      type_hint: text
    - name: tenant_id
      description: Azure Tenant ID
      default: tenant_id
      type_hint: text
    - name: location
      description: Location
      default: eastus
      type_hint: text
    - name: resource_group_name
      description: Resource Group
      default: vmseries-rg
      type_hint: text
    - name: vnet_name
      description: VNET Name
      default: vmseries-vnet
      type_hint: text
    - name: address_space
      description: VNET Address Space
      default: 10.0.0.0/16
      type_hint: text
    - name: subnet_names
      description: Subnet Names - 3 required
      default: "mgmt,untrust,trust"
      type: text
    - name: Subnet Address Spaces - 3 required
      description: Subnet Prefixes - 3 required
      default: "10.0.0.0/24,10.0.1.0/24,10.0.2.0/24"
      type_hint: text
    - name: fw_nsg_source_prefix
      description: Mgmt NSG Source Prefix
      default: "0.0.0.0/0"
      type_hint: text
    - name: internal_lb_address
      description: Internal Load Balancer Address - must be in last subnet space
      default: "10.0.2.100"
      type_hint: text
    - name: public_lb_ports
      description: Public Load Balancer Allowed Ports (for every port entered, a new rule is created)
      default: 80,443,22,3389
      type_hint: text
    - name: fw_names
      description: FW names (for every name entered, a new VM is created)
      default: "vmseries-fw1,vmseries-fw2"
      type_hint: text
    - name: fw_username
      description: FW Username (do not use admin or root)
      default: paloalto
      type_hint: text
    - name: fw_password
      description: FW Password (1 upper & lower, 1 special, no slash or hyphen)
      default:
      type_hint: text
    - name: fw_license
      description: FW License
      default:
      type_hint: dropdown
      dd_list:
       - key: BYOL
         value: byol
       - key: PAYG-Bundle1
         value: bundle1
       - key: PAYG-Bundle2
         value: bundle2
    - name: prefix
      description: Appends a prefix to all newly created resources
      default: ""
      type_hint: text
    