# This is an example .meta-cnc.yaml file. This will allow Panhandler to consume this terraform project

# this is the name of this skillet, should be unique within a given repository
name: azure_multifw_3nic_intlb_extlb

# label should be a human readable label that conveys what this skillet will do 
label: Azure Multi-FW

# description is a longer more informative version of a label
description: Creates multiple firewalls with optional public & internal load balancers.

# type instructs Panhandler how to consume this skillet
type: terraform

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, lables can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  terraform_provider: azure


# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:
    - name: subscription_id
      description: Azure Subscription ID
      default: client_secret
      type_hint: text
    - name: client_id
      description: Azure Client ID
      default: client_id
      type_hint: text
    - name: client_secret
      description: Azure Client Secret
      default: client_secret
      type_hint: text
    - name: tenant_id
      description: Azure Tenant ID
      default: tenant_id
      type_hint: text
    - name: location
      description: Location
      default: eastus
      type_hint: text
    - name: vnet_option
      description: VNET Options
      default:
      type_hint: dropdown
      dd_list:
       - key: Create a new VNET
         value: "1,1"
       - key:  Use existing VNET with new subnets
         value: "0,1"
       - key: Use existing VNET with existing subnets
         value: "0,0"
    - name: vnet_rg
      description: VNET Resource Group
      default: 
      type_hint: text
    - name: vnet_name
      description: VNET Name
      default: vmseries-vnet
      type_hint: text
    - name: vnet_prefix
      description: VNET Address Space
      default: 10.0.0.0/16
      type_hint: text
    - name: vnet_subnet_names
      description: Subnet Names - 3 required
      default: "mgmt,untrust,trust"
      type: text
    - name: vnet_subnet_prefixes
      description: Subnet Prefixes - 3 required
      default: "10.0.0.0/24,10.0.1.0/24,10.0.2.0/24"
      type_hint: text
    - name: appgw_publb_intlb_option
      description: Azure Additional Resource Options
      default:
      type_hint: dropdown
      dd_list:
       - key: AppGW, Public LB, Internal LB
         value: "1,1,1"
       - key: AppGW, Public LB
         value: "1,1,0"
       - key: AppGW, Internal LB
         value: "1,0,1"
       - key: AppGW
         value: "1,0,0"
       - key: Public LB, Internal LB
         value: "0,1,1"
       - key: Public LB
         value: "0,1,0"
       - key: Internal LB
         value: "0,0,1"
       - key: None
         value: "0,0,0"
    - name: public_lb_ports
      description: Public Load Balancer Allowed Ports (for every port entered, a new rule is created)
      default: 80,443,22,3389
      type_hint: text
    - name: internal_lb_address
      description: Internal Load Balancer Address - must be in last subnet space
      default: "10.0.2.100"
      type_hint: text
    - name: fw_rg
      description: FW Resource Group (do not use existing RG)
      default: vmseries-rg
      type_hint: text
    - name: fw_names
      description: FW names (for every name entered, a new VM is created)
      default: "vmseries-fw1,vmseries-fw2"
      type_hint: text
    - name: fw_panos_version
      description: FW PAN-OS Version
      default: eastus
      type_hint: dropdown
      dd_list:
       - key: latest
         value: latest
       - key: "8.1.0"
         value: "8.1.0"
       - key: "8.0.0"
         value: "8.0.0"
       - key: "7.1.0"
         value: "7.1.1"
    - name: fw_license
      description: FW License
      default:
      type_hint: dropdown
      dd_list:
       - key: BYOL
         value: byol
       - key: PAYG-Bundle1
         value: bundle1
       - key: PAYG-Bundle2
         value: bundle2
    - name: create_public_ips
      description: FW Public IP Options
      default:
      type_hint: dropdown
      dd_list:
       - key: Apply to MGMT & UNTRUST
         value: "1,1"
       - key: MGMT Only
         value: "1,0"
       - key: Untrust Only
         value: "0,1"
       - key: None
         value: "0,0"
    - name: fw_username
      description: FW Username (do not use admin or root)
      default: paloalto
      type_hint: text
    - name: fw_password
      description: FW Password (1 upper & lower, 1 special, no slash or hyphen)
      default:
      type_hint: text
    - name: fw_nsg_source_prefix
      description: Mgmt NSG Source Prefix
      default: "0.0.0.0/0"
      type_hint: text